  environment:
    - DB_HOST=db
    - DB_NAME=app
    - DB_USER=postgres
    - DB_PASS=supersecretpassword
  depends_on:
    - db
db:
  image: postgres:10-alpine
  environment:
    - POSTGRES_DB=app
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=supersecretpassword
